### ISSUE TITLE
I downloaded the project and opened in visual studio but unable to run the tests

### ISSUE THREAD

**Issue by MuraliGitHub1204** [projectcodify/refit-demo#1]
I downloaded the project and opened in visual studio but unable to run the tests. It is saying no Tests identified. I downloaded from github only. Any help is appreciated.

**Comment by MuraliGitHub1204** [comment]
@vivekse  Can you pls do the needful on the above issue. I downloaded your code and the tests are not showing in test explorer.

**Comment by projectcodify** [comment]
@MuraliGitHub1204  there are no tests in the repository. Which tests are you expecting to show up?
